apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kad-role
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - apps
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - extensions
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch